name: 'Top Issues action'
description: 'Labels and displays the top-upvoted (i.e. 👍) issues and pull requests in your repository.'
author: 'Rick Staa'
inputs:
  # General inputs.
  github_token:
    description: 'Token used for authorizing interactions with the repository.  Typically the `GITHUB_TOKEN` secret.'
    required: true
    default: ${{ github.token }}
  top_list_size:
    required: false
    description: 'The number of top issues to show.'
    default: '5'
  subtract_negative:
    required: false
    description: 'Subtract negative from positive reactions to get the total count.'
    default: 'true'
  dry_run:
    required: false
    description: 'Run the action without actually creating the labels and dashboard.'
    default: 'false'
  label:
    required: false
    description: 'Label top issues.'
    default: 'false'
  dashboard:
    required: false
    description: 'Create a dashboard that displays the top issues and pull requests.'
    default: 'true'
  # Dashboard related inputs,
  dashboard_title:
    required: false
    description: 'Dashboard title.'
    default: 'Top Issues Dashboard'
  dashboard_label:
    required: false
    description: 'The label used for the top issues dashboard.'
    default: ':star: top issues dashboard'
  dashboard_label_description:
    required: false
    description: 'The description used for the top issues dashboard label.'
    default: 'Top issues dashboard.'
  dashboard_label_colour:
    required: false
    description: 'The colour used for the top issues dashboard label.'
    default: '#006B75'
  hide_dashboard_footer:
    required: false
    description: 'Hide dashboard footer.'
    default: 'false'
  # Top issues related inputs.
  top_issues:
    required: false
    description: 'Display top issues.'
    default: 'true'
  top_issue_label:
    required: false
    description: 'The label used for labelling  top issues.'
    default: ':star: top issue'
  top_issue_label_description:
    required: false
    description: 'The description used for the top issue label.'
    default: 'Top issue.'
  top_issue_label_colour:
    required: false
    description: 'The colour used for the top issue label.'
    default: '#027E9D'
  # Top bugs related inputs.
  top_bugs:
    required: false
    description: 'Display top bugs.'
    default: 'false'
  bug_label:
    required: false
    description: 'The label that is used for bug issues.'
    default: 'bug'
  top_bug_label:
    required: false
    description: 'The label used for labelling  top bugs.'
    default: ':star: top bug'
  top_bug_label_description:
    required: false
    description: 'The description used for the top bug label.'
    default: 'Top bug.'
  top_bug_label_colour:
    required: false
    description: 'The colour used for the top bug label.'
    default: '#B60205'
  # Top features related inputs.
  top_features:
    required: false
    description: 'Display top feature requests.'
    default: 'false'
  feature_label:
    required: false
    description: 'The label that is used for feature requests.'
    default: 'enhancement'
  top_feature_label:
    required: false
    description: 'The label used for labelling top feature request issues.'
    default: ':star: top feature'
  top_feature_label_description:
    required: false
    description: 'The description used for the top feature request label.'
    default: 'Top feature request.'
  top_feature_label_colour:
    required: false
    description: 'The colour used for the top feature request label.'
    default: '#0E8A16'
  # Top pull request related inputs.
  top_pull_requests:
    required: false
    description: 'Display top pull requests.'
    default: 'false'
  top_pull_requests_label:
    required: false
    description: 'The label used for labelling  top pull request.'
    default: ':star: top pull request'
  top_pull_request_label_description:
    required: false
    description: 'The description used for the top pull request label.'
    default: 'Top pull request.'
  top_pull_request_label_colour:
    required: false
    description: 'The colour used for the top pull request label.'
    default: '#41A285'
branding:
  color: 'blue'
  icon: 'arrow-up'
runs:
  using: 'node16'
  main: 'dist/index.js'
