/**
 * @file Contains the action constants.
 */
export const DASHBOARD_HEADER = `<!--
This dashboard was generated by the [top-issues-action](https://github.com/rickstaa/top-issues-action) action.
-->

A simple dashboard that lists the top issues/bugs/features and pull requests.`
export const DASHBOARD_FOOTER = `> Created by the [rickstaa/top-issues-action](https://github.com/rickstaa/top-issues-action) action (last update: ${new Date().toLocaleString()}).`
